// ~~ Generated by projen. To modify, edit .projenrc.ts and run "yarn projen".
// @ts-check
/** @type {import('@yarnpkg/types')} */
const { defineConfig } = require(`@yarnpkg/types`);

module.exports = defineConfig({
  async constraints({ Yarn }) {
    const root = Yarn.workspace({ cwd: '.' });
    for (const ident of ["typescript","eslint","eslint-import-resolver-typescript","eslint-plugin-import","eslint-plugin-jest","eslint-plugin-jsdoc","@cdklabs/eslint-plugin","@stylistic/eslint-plugin","@typescript-eslint/eslint-plugin","@typescript-eslint/parser","prettier","jest-junit","nx"]) {
      const expected = root.manifest.devDependencies?.[ident];
      if (!expected) continue;
      for (const workspace of Yarn.workspaces()) {
        if (workspace.manifest.devDependencies?.[ident]) {
          workspace.set(['devDependencies', ident], expected);
        }
      }
    }
  },
});
